export enum NotificationType {
    COMMENT_ON_POST = 'COMMENT_ON_POST',
    REPLY_TO_COMMENT = 'REPLY_TO_COMMENT',
    ORDER_ASSIGNED = 'ORDER_ASSIGNED',
    ORDER_COMPLETED = 'ORDER_COMPLETED',
    USER_REVIEWED = 'USER_REVIEWED',
    USER_MESSAGE = 'USER_MESSAGE',
    REVIEWED_PROFILE='REVIEWED_PROFILE'
  }
  