export enum NotificationType {
    COMMENT_ON_POST = 'COMMENT_ON_POST', //Done 
    REPLY_TO_COMMENT = 'REPLY_TO_COMMENT', // Done 
    ORDER_ASSIGNED = 'ORDER_ASSIGNED',
    ORDER_COMPLETED = 'ORDER_COMPLETED',
    USER_REVIEWED = 'USER_REVIEWED', //Done 
    USER_MESSAGE = 'USER_MESSAGE',
    VISITED_PROFILE='VISITED_PROFILE' //Done
  }
  