export enum UserFields {
    ID = '_id',
    NAME = 'name',
    EMAIL = 'email',
    PASSWORD = 'password',
    ABOUT = 'about',
    VERIFY = 'verify',
    ROLE = 'role',
    OTP = 'otp',
    IS_OTP_USED = 'isOtpUsed',
    AVATAR = 'avatar',
    PHONE = 'phone',
    TASK_COMPLETED = 'task_completed',
    MY_ORDERS = 'my_orders',
    RATINGS = 'ratings',
    ZIP_CODE = 'zip_code',
    CITY = 'city',
    CREATED_AT = 'createdAt',
    UPDATED_AT = 'updatedAt',
    VERSION = '__v',
    PROFESSION = 'profession',
    ADDRESS = 'address',
  }
export enum PostFields {
    ID = '_id',
    TITLE = 'title',
    DESCRIPTION = 'description',
    IMAGES = 'images',
    CITY = 'city',
    STREET_ADDRESS = 'streetAddress',
    STATE = 'state',
    ZIP_CODE = 'zipCode',
    USER_ID = 'userId',
    IS_URGENT = 'isUrgent',
    IS_HELP_FREE = 'isHelpFree',
    OBO = 'obo',
    PRICE = 'price',
    LOCATION = 'location',
    CREATED_AT = 'createdAt',
    UPDATED_AT = 'updatedAt',
    VERSION = '__v',
  }
  
  